---
# tasks file for roles/webserver-role
- name: Load OS-specific variables
  ansible.builtin.include_vars: "os/{{ ansible_facts['os_family'] }}.yml"

- name: Install nginx
  package:
    name: "{{ nginx_package }}"
    state: present

- name: Ensure nginx root directory exists
  file:
    path: "{{ nginx_root }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Fix Selinux context for nginx root (Almalinux/RHEL)
  ansible.posix.seboolean:
    name: httpd_read_user_content
    state: true
    persistent: true
  when: ansible_os_family == 'RedHat'

- name: Deploy index.html template
  template:
    src: index.html.j2
    dest: "{{ nginx_root  }}/index.html"
  notify: restart nginx

- name: Deploy nginx server block
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_path }}"
  notify: restart nginx

- name: Test nginx configuration syntax
  command: nginx -t
  register: nginx_test
  changed_when: false
  failed_when: nginx_test.rc !=0

- name: Ensure nginx is running
  service:
    name: "{{  nginx_service_name }}"
    state: started
    enabled: yes
